### ISSUE TITLE
Cannot build on OSX 10.9.5

### ISSUE THREAD

**Issue by jkds** [tobert/cassandra-docker#16]
After making some modifications to the original entrypoint I attempted to execute a go build on OSX 10.9.5
Following the pre-requisite steps to retrieve sprok before doing this failed.

Console output:

    ✔ ~/Development/Projects/cassandra-docker [jkds-modified L|●2✚ 3…13]
    11:25 $ go get -u github.com/tobert/sprok
    # github.com/tobert/sprok
    ../../Tools/go/src/github.com/tobert/sprok/process.go:143: undefined: syscall.Setresgid
    ../../Tools/go/src/github.com/tobert/sprok/process.go:150: undefined: syscall.Setresuid
    ✘-2 ~/Development/Projects/cassandra-docker [jkds-modified L|●2✚ 3…13]
    11:25 $ go version
    go version go1.4 darwin/amd64
    ✔ ~/Development/Projects/cassandra-docker [jkds-modified L|●2✚ 3…13]

I had previously tried the same with go 1.4.2 but encountered the same issue.

**Comment by tobert** [comment]
I added support for OSX to sprok in https://github.com/tobert/sprok/commit/93fb8cf9637326a0ecc3309f06280132766c4604

Try `go get -u gopkg.in/yaml.v2` then build again.

**Comment by jkds** [comment]
Awesome, many thanks!
